// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5nf1DeKl54xsHcbvmrhTFJX0Fj_oDSmc',
    appId: '1:102332206836:web:380d8b00d552001a6698a1',
    messagingSenderId: '102332206836',
    projectId: 'my-website-bf9e6',
    authDomain: 'my-website-bf9e6.firebaseapp.com',
    storageBucket: 'my-website-bf9e6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYb4TZgLvriB62UKfe2c7Yhp0_CVUYFIo',
    appId: '1:102332206836:android:4d2362906c11cf166698a1',
    messagingSenderId: '102332206836',
    projectId: 'my-website-bf9e6',
    storageBucket: 'my-website-bf9e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApFapWBdVWR_ur1jM8Vwp-eaIWtaHx5Lg',
    appId: '1:102332206836:ios:a9b3f8f985427e256698a1',
    messagingSenderId: '102332206836',
    projectId: 'my-website-bf9e6',
    storageBucket: 'my-website-bf9e6.firebasestorage.app',
    iosBundleId: 'com.example.myWebSite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApFapWBdVWR_ur1jM8Vwp-eaIWtaHx5Lg',
    appId: '1:102332206836:ios:4d74a29505c0ff1c6698a1',
    messagingSenderId: '102332206836',
    projectId: 'my-website-bf9e6',
    storageBucket: 'my-website-bf9e6.firebasestorage.app',
    iosBundleId: 'com.example.myWebSite',
  );
}